%%BEGINHEADER
% Program: matlab
% MClust version: MClust 4.0.5; 2014/Jan/28 (BETA)
% Date: 30-Jan-2014 10:35:23
% Directory: E:\Home\adredish\Products\MClust\MClust-4.0\Samples-to-test-with\basic
% T-file
% Output from MClust
% Time of spiking stored in timestamps (tenths of msecs)
% as unsigned integer: uint32
%%ENDHEADER
Ù—•ÙœLÙ ‰Ù¦ÊÙ²€ÙîÙÙöóÙÿÚôÚ	+Ú¨Ú±Ú†Ú÷Ú4–Ú9jÚ;“Ú>áÚC™Ú•Ú›æÚ ˜Ú¥àÚ¿`ÚÅ«ÚÊœÚÙ/Úå*ÚõdÚú×ÛŠÛÛ1Û9@ÛGŒÛH|ÛLÜÛO–ÛRÛTçÛZ
Û]åÛ_=Û_þÛb·ÛfÛhÉÛjáÛl7ÛtªÛuNÛ”wÛ•ÈÛšÛœ'Û¦…Ûª†ÛÆCÛÈ©ÛËóÛÏòÛÜ‹Ûà‹ÛêëÛí—Ûñ&Ûú-ÛûþÜ Ü‘ÜºÜÜÜ0pÜ8¡Ü<ÈÜ@wÜJîÜLˆÜX7ÜYoÜZõÜ\…Ü^uÜbÈÜfiÜh¢Üi—ÜnÌÜpíÜruÜwíÜ{ÉÜ~QÜËÜƒÕÜ…KÜ‡{ÜŠÜ’úÜ—6Ü›Ü«¼Ü®'Ü½¯Ü¿1ÜÀ6ÜÃÜÄàÜÆsÜÈmÝ!xÝSÝZ,Ý·òÝÁsÝÈÍÞ÷©à4
à=ìáQüá…Åá÷4âˆâ(gâ0+â9Óâ?üâI¹âRÐâW\â_Ýâdâ¬ â»2ãUaäñä5/ä=ä@¦åº
çÅç!öç%cç@®ç­?çöÄèzzéy#é…Þé‹æé•þé¨¹é¹Eêtêê<ÏêŠëI”ëOòëTDëZíqívîíî°SîÃ“îÈ%îÑ:îÖyîèéîê¿ï·ïqäïyÍï~}ï•´ï›kï¢‰ï¥íïªôï½ƒïÏ_